## Assignment 6

In [151]:
import pandas as pd
import numpy as np

# Task -1

In [152]:
all_27_lang = ["af-ZA.jsonl", "da-DK.jsonl", "de-DE.jsonl", "en-US.jsonl", "es-ES.jsonl", "fr-FR.jsonl", "fi-FI.jsonl", "hu-HU.jsonl", "is-IS.jsonl", "it-IT.jsonl", "jv-ID.jsonl",
    "lv-LV.jsonl", "ms-MY.jsonl", "nb-NO.jsonl", "nl-NL.jsonl", "pl-PL.jsonl", "pt-PT.jsonl", "ro-RO.jsonl", "ru-RU.jsonl", "sl-SL.jsonl", "sv-SE.jsonl", "sq-AL.jsonl", "sw-KE.jsonl", "tl-PH.jsonl", "tr-TR.jsonl", "vi-VN.jsonl", "cy-GB.jsonl"]

In [153]:
## we had made a list containing all the 27 required language so that we can go loop and concat them easily.

In [154]:
dataframes = []
for jason_file in all_27_lang:
    df = pd.read_json(jason_file, lines = True)
    dataframes.append(df)
full_df = pd.concat(dataframes, axis=0)

In [155]:
full_df

,id,locale,partition,scenario,intent,utt,annot_utt,worker_id,slot_method,judgments
0,0,af-ZA,test,alarm,alarm_set,maak my wakker om vyf v. m. die week,maak my wakker om [time : vyf v. m.] [date : d...,37,"[{'slot': 'time', 'method': 'localization'}, {...","[{'worker_id': '20', 'intent_score': 1, 'slots..."
1,1,af-ZA,train,alarm,alarm_set,maak my wakker nege-uur v. m. op vrydag,maak my wakker [time : nege-uur v. m.] op [dat...,20,"[{'slot': 'time', 'method': 'translation'}, {'...","[{'worker_id': '40', 'intent_score': 1, 'slots..."
2,2,af-ZA,train,alarm,alarm_set,stel 'n alarm vir twee ure van nou af,stel 'n alarm vir [time : twee ure van nou af],20,"[{'slot': 'time', 'method': 'translation'}]","[{'worker_id': '64', 'intent_score': 1, 'slots..."
3,3,af-ZA,test,audio,audio_volume_mute,stil,stil,40,[],"[{'worker_id': '45', 'intent_score': 1, 'slots..."
4,4,af-ZA,train,audio,audio_volume_mute,janneman stilte,janneman stilte,40,[],"[{'worker_id': '45', 'intent_score': 1, 'slots..."
...,...,...,...,...,...,...,...,...,...,...
16516,17176,cy-GB,train,email,email_query,a oes gennyf ebyst,a oes gennyf ebyst,0,[],"[{'worker_id': '4', 'intent_score': 1, 'slots_..."
16517,17177,cy-GB,train,email,email_query,pa ebyst sy'n newydd,pa ebyst sy'n newydd,0,[],"[{'worker_id': '2', 'intent_score': 1, 'slots_..."
16518,17178,cy-GB,train,email,email_query,a oes gennyf unrhyw ebyst newydd oddi wrth john,a oes gennyf unrhyw ebyst newydd oddi wrth [pe...,0,"[{'slot': 'person', 'method': 'unchanged'}]","[{'worker_id': '0', 'intent_score': 1, 'slots_..."
16519,17179,cy-GB,test,email,email_query,ydy john wedi anfon ebost i fi,ydy [person : john] wedi anfon ebost i fi,5,"[{'slot': 'person', 'method': 'unchanged'}]","[{'worker_id': '5', 'intent_score': 1, 'slots_..."
16520,17180,cy-GB,train,email,email_query,gwiriwch ebost wrth john,gwiriwch ebost wrth [person : john],5,"[{'slot': 'person', 'method': 'unchanged'}]","[{'worker_id': '0', 'intent_score': 1, 'slots_..."

In [156]:
full_df.describe()

                  id      worker_id
count  446067.000000  446067.000000
mean     8564.718661      28.575891
std      4955.580201      72.140892
min         0.000000       0.000000
25%      4273.000000       6.000000
50%      8534.000000      13.000000
75%     12837.000000      27.000000
max     17180.000000     690.000000

In [157]:
full_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 446067 entries, 0 to 16520
Data columns (total 10 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   id           446067 non-null  int64
 1   locale       446067 non-null  object
 2   partition    446067 non-null  object
 3   scenario     446067 non-null  object
 4   intent       446067 non-null  object
 5   utt          446067 non-null  object
 6   annot_utt    446067 non-null  object
 7   worker_id    446067 non-null  int64
 8   slot_method  429546 non-null  object
 9   judgments    429546 non-null  object
dtypes: int64(2), object(8)
memory usage: 37.4+ MB

In [158]:
## Now, as per question we have to build the dataframe for 27 such languages its complicated to do that one by one
## so lets make a list and do it by for loop and concat them easily..

In [159]:
df_new = full_df[['locale','partition','utt']]
df_new

      locale partition                                              utt
0      af-ZA      test             maak my wakker om vyf v. m. die week
1      af-ZA     train          maak my wakker nege-uur v. m. op vrydag
2      af-ZA     train            stel 'n alarm vir twee ure van nou af
3      af-ZA      test                                             stil
4      af-ZA     train                                  janneman stilte
...      ...       ...                                              ...
16516  cy-GB     train                               a oes gennyf ebyst
16517  cy-GB     train                             pa ebyst sy'n newydd
16518  cy-GB     train  a oes gennyf unrhyw ebyst newydd oddi wrth john
16519  cy-GB      test                   ydy john wedi anfon ebost i fi
16520  cy-GB     train                         gwiriwch ebost wrth john

[446067 rows x 3 columns]

In [160]:
df_new['Token']=df_new['utt'].str.split()

C:\Users\DELL\AppData\Local\Temp\ipykernel_2228\4238816034.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_new['Token']=df_new['utt'].str.split()

In [161]:
df_new

,locale,partition,utt,Token
0,af-ZA,test,maak my wakker om vyf v. m. die week,"[maak, my, wakker, om, vyf, v., m., die, week]"
1,af-ZA,train,maak my wakker nege-uur v. m. op vrydag,"[maak, my, wakker, nege-uur, v., m., op, vrydag]"
2,af-ZA,train,stel 'n alarm vir twee ure van nou af,"[stel, 'n, alarm, vir, twee, ure, van, nou, af]"
3,af-ZA,test,stil,[stil]
4,af-ZA,train,janneman stilte,"[janneman, stilte]"
...,...,...,...,...
16516,cy-GB,train,a oes gennyf ebyst,"[a, oes, gennyf, ebyst]"
16517,cy-GB,train,pa ebyst sy'n newydd,"[pa, ebyst, sy'n, newydd]"
16518,cy-GB,train,a oes gennyf unrhyw ebyst newydd oddi wrth john,"[a, oes, gennyf, unrhyw, ebyst, newydd, oddi, ..."
16519,cy-GB,test,ydy john wedi anfon ebost i fi,"[ydy, john, wedi, anfon, ebost, i, fi]"
16520,cy-GB,train,gwiriwch ebost wrth john,"[gwiriwch, ebost, wrth, john]"

# Task -2

In [162]:
X1 = df_new[df_new['partition'] == 'train']

In [163]:
X1

,locale,partition,utt,Token
1,af-ZA,train,maak my wakker nege-uur v. m. op vrydag,"[maak, my, wakker, nege-uur, v., m., op, vrydag]"
2,af-ZA,train,stel 'n alarm vir twee ure van nou af,"[stel, 'n, alarm, vir, twee, ure, van, nou, af]"
4,af-ZA,train,janneman stilte,"[janneman, stilte]"
5,af-ZA,train,stop,[stop]
6,af-ZA,train,janneman onderbreek dit vir tien sekondes,"[janneman, onderbreek, dit, vir, tien, sekondes]"
...,...,...,...,...
16515,cy-GB,train,anfon helo drwy whatsapp i vikki,"[anfon, helo, drwy, whatsapp, i, vikki]"
16516,cy-GB,train,a oes gennyf ebyst,"[a, oes, gennyf, ebyst]"
16517,cy-GB,train,pa ebyst sy'n newydd,"[pa, ebyst, sy'n, newydd]"
16518,cy-GB,train,a oes gennyf unrhyw ebyst newydd oddi wrth john,"[a, oes, gennyf, unrhyw, ebyst, newydd, oddi, ..."
16520,cy-GB,train,gwiriwch ebost wrth john,"[gwiriwch, ebost, wrth, john]"

In [168]:
X1_train = X1.drop(['locale','partition','Token'], axis = 1).astype(str)

In [169]:
X1_train.shape

(310878, 1)

In [170]:
X1_train

                                                   utt
1              maak my wakker nege-uur v. m. op vrydag
2                stel 'n alarm vir twee ure van nou af
4                                      janneman stilte
5                                                 stop
6            janneman onderbreek dit vir tien sekondes
...                                                ...
16515                 anfon helo drwy whatsapp i vikki
16516                               a oes gennyf ebyst
16517                             pa ebyst sy'n newydd
16518  a oes gennyf unrhyw ebyst newydd oddi wrth john
16520                         gwiriwch ebost wrth john

[310878 rows x 1 columns]

In [171]:
X1_train = X1_train.values

In [172]:
X1_train

array([['maak my wakker nege-uur v. m. op vrydag'],
       ["stel 'n alarm vir twee ure van nou af"],
       ['janneman stilte'],
       ...,
       ["pa ebyst sy'n newydd"],
       ['a oes gennyf unrhyw ebyst newydd oddi wrth john'],
       ['gwiriwch ebost wrth john']], dtype=object)

In [173]:
y1_train = X1['locale'].values

In [174]:
y1_train.shape

(310878,)

## Now by using Multinomial

In [175]:
from sklearn.naive_bayes import MultinomialNB

In [176]:
X1_train = X1_train.reshape(1, 310878)
X1_train = X1_train[0]

In [177]:
X1_train.size

310878

In [178]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.pipeline import make_pipeline
model = make_pipeline(TfidfVectorizer(),MultinomialNB())
model.fit(X1_train,y1_train)

Pipeline(steps=[('tfidfvectorizer', TfidfVectorizer()),
                ('multinomialnb', MultinomialNB())])

In [179]:
new_data = ['unrhyw ebyst newydd oddi wrth']
predictions = model.predict(new_data)

print("Predictions:", predictions)

Predictions: ['cy-GB']

In [180]:
df_new['partition'].value_counts()

partition
train    310878
test      80298
dev       54891
Name: count, dtype: int64

In [181]:
X2 = df_new[df_new['partition']=='dev']

In [182]:
X2

,locale,partition,utt,Token
11,af-ZA,dev,skakel die ligte af asseblief,"[skakel, die, ligte, af, asseblief]"
17,af-ZA,dev,verdof die ligte in die gang,"[verdof, die, ligte, in, die, gang]"
24,af-ZA,dev,maak die vertrek donkerder,"[maak, die, vertrek, donkerder]"
26,af-ZA,dev,maak die woonstel skoon,"[maak, die, woonstel, skoon]"
30,af-ZA,dev,skoonmaak is goed stof is so sleg doen nou jou...,"[skoonmaak, is, goed, stof, is, so, sleg, doen..."
...,...,...,...,...
16462,cy-GB,dev,adroddwch unrhyw e-byst newydd,"[adroddwch, unrhyw, e-byst, newydd]"
16478,cy-GB,dev,sawl neges heb eu darllen sydd gennyf i,"[sawl, neges, heb, eu, darllen, sydd, gennyf, i]"
16481,cy-GB,dev,ymateb i'r ebost dw'i newydd derbyn,"[ymateb, i'r, ebost, dw'i, newydd, derbyn]"
16494,cy-GB,dev,wnaeth bert ysgrifennu ataf i heddiw,"[wnaeth, bert, ysgrifennu, ataf, i, heddiw]"
16508,cy-GB,dev,beth yw'r cyfeiriad ar gyfer alex,"[beth, yw'r, cyfeiriad, ar, gyfer, alex]"

In [183]:
y2_train = X2['utt'].values

In [184]:
prediction = model.predict(y2_train)

In [185]:
prediction

array(['af-ZA', 'af-ZA', 'af-ZA', ..., 'cy-GB', 'cy-GB', 'cy-GB'],
      dtype='<U5')

In [186]:
y_test = X2['locale'].values

In [187]:
from sklearn.metrics import classification_report

In [188]:
print(classification_report(prediction ,y_test))

              precision    recall  f1-score   support

       af-ZA       0.98      0.91      0.94      2192
       cy-GB       0.99      1.00      0.99      2019
       da-DK       0.96      0.94      0.95      2075
       de-DE       0.98      1.00      0.99      2006
       en-US       0.99      0.95      0.97      2112
       es-ES       0.98      0.99      0.98      2023
       fi-FI       0.98      1.00      0.99      2005
       fr-FR       0.99      0.99      0.99      2032
       hu-HU       0.98      1.00      0.99      1994
       is-IS       0.99      1.00      0.99      2016
       it-IT       0.99      0.99      0.99      2039
       jv-ID       0.98      0.99      0.98      2030
       lv-LV       0.99      1.00      0.99      2015
       ms-MY       0.99      0.98      0.99      2045
       nb-NO       0.94      0.96      0.95      1975
       nl-NL       0.97      0.98      0.97      2018
       pl-PL       0.98      0.99      0.99      2028
       pt-PT       0.99      0.99      0.99      2033
       ro-RO       0.99      1.00      0.99      2015
       ru-RU       0.99      1.00      1.00      2021
       sl-SL       0.99      1.00      0.99      2020
       sq-AL       0.99      1.00      0.99      2018
       sv-SE       0.98      0.97      0.98      2057
       sw-KE       0.99      1.00      1.00      2020
       tl-PH       0.99      0.99      0.99      2034
       tr-TR       0.99      1.00      0.99      2019
       vi-VN       1.00      1.00      1.00      2030

    accuracy                           0.98     54891
   macro avg       0.98      0.98      0.98     54891
weighted avg       0.98      0.98      0.98     54891

# Task -3

In [189]:
Map = {
    'language': [
        'af-ZA.jsonl', 'da-DK.jsonl', 'de-DE.jsonl', 'en-US.jsonl', 'es-ES.jsonl',
        'fr-FR.jsonl', 'fi-FI.jsonl', 'hu-HU.jsonl', 'is-IS.jsonl', 'it-IT.jsonl',
        'jv-ID.jsonl', 'lv-LV.jsonl', 'ms-MY.jsonl', 'nb-NO.jsonl', 'nl-NL.jsonl',
        'pl-PL.jsonl', 'pt-PT.jsonl', 'ro-RO.jsonl', 'ru-RU.jsonl', 'sl-SL.jsonl',
        'sv-SE.jsonl', 'sq-AL.jsonl', 'sw-KE.jsonl', 'tl-PH.jsonl', 'tr-TR.jsonl',
        'vi-VN.jsonl', 'cy-GB.jsonl'
    ],
    'continent': [
        'Africa',  # af-ZA
        'Europe',  # da-DK
        'Europe',  # de-DE
        'North America',  # en-US
        'Europe',  # es-ES
        'Europe',  # fr-FR
        'Europe',  # fi-FI
        'Europe',  # hu-HU
        'Europe',  # is-IS
        'Europe',  # it-IT
        'Asia',    # jv-ID
        'North America',  # lv-LV
        'Asia',    # ms-MY
        'Europe',  # nb-NO
        'Europe',  # nl-NL
        'Europe',  # pl-PL
        'Europe',  # pt-PT
        'Europe',  # ro-RO
        'Europe',  # ru-RU
        'Europe',  # sl-SL
        'South America',  # sv-SE
        'Europe',  # sq-AL
        'Africa',  # sw-KE
        'Asia',    # tl-PH
        'Asia',    # tr-TR
        'Asia',    # vi-VN
        'Europe'   # cy-GB
    ]
}

In [190]:
df = pd.DataFrame(Map)
grouped_data = df.groupby('continent')['language'].apply(list).reset_index()
print(grouped_data)

       continent                                           language
0         Africa                         [af-ZA.jsonl, sw-KE.jsonl]
1           Asia  [jv-ID.jsonl, ms-MY.jsonl, tl-PH.jsonl, tr-TR....
2         Europe  [da-DK.jsonl, de-DE.jsonl, es-ES.jsonl, fr-FR....
3  North America                         [en-US.jsonl, lv-LV.jsonl]
4  South America                                      [sv-SE.jsonl]

In [191]:
df

       language      continent
0   af-ZA.jsonl         Africa
1   da-DK.jsonl         Europe
2   de-DE.jsonl         Europe
3   en-US.jsonl  North America
4   es-ES.jsonl         Europe
5   fr-FR.jsonl         Europe
6   fi-FI.jsonl         Europe
7   hu-HU.jsonl         Europe
8   is-IS.jsonl         Europe
9   it-IT.jsonl         Europe
10  jv-ID.jsonl           Asia
11  lv-LV.jsonl  North America
12  ms-MY.jsonl           Asia
13  nb-NO.jsonl         Europe
14  nl-NL.jsonl         Europe
15  pl-PL.jsonl         Europe
16  pt-PT.jsonl         Europe
17  ro-RO.jsonl         Europe
18  ru-RU.jsonl         Europe
19  sl-SL.jsonl         Europe
20  sv-SE.jsonl  South America
21  sq-AL.jsonl         Europe
22  sw-KE.jsonl         Africa
23  tl-PH.jsonl           Asia
24  tr-TR.jsonl           Asia
25  vi-VN.jsonl           Asia
26  cy-GB.jsonl         Europe

In [195]:
from sklearn.feature_extraction.text import TfidfVectorizer
vectorizer = TfidfVectorizer()
X_vectorized = vectorizer.fit_transform(X)

In [ ]:
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis as LDA
from sklearn.discriminant_analysis import QuadraticDiscriminantAnalysis as QDA
from sklearn.base import BaseEstimator, ClassifierMixin

class RDA(BaseEstimator, ClassifierMixin):
    def __init__(self, lambda_param=0.5):
        self.lambda_param = lambda_param
        self.lda = LDA()
        self.qda = QDA()

    def fit(self, X, y):
        self.lda.fit(X, y)
        self.qda.fit(X, y)
        return self

    def predict(self, X):
        lda_probs = self.lda.predict_proba(X)
        qda_probs = self.qda.predict_proba(X)
        combined_probs = (1 - self.lambda_param) * lda_probs + self.lambda_param * qda_probs
        return np.argmax(combined_probs, axis=1)

    def predict_proba(self, X):
        lda_probs = self.lda.predict_proba(X)
        qda_probs = self.qda.predict_proba(X)
        combined_probs = (1 - self.lambda_param) * lda_probs + self.lambda_param * qda_probs
        return combined_probs